language: node_js

node_js:
  - "6.10"
  - "6.9"
  - "6.8"
  - "6.7"
  - "6.6"
  - "6.5"
  - "6.4"
  - "6.3"
  - "6.2"
  - "6.1"
  - "6.0"

notifications:
  email:
    on_success: always
    on_failure: always

install:
  - npm install -g codecov

script:
  - npm install
  - npm run test

after_success:
  # publish coverage info to coveralls
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && [[ "${TRAVIS_JOB_NUMBER}" = *".1"* ]]; then
      cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js;
    fi
