language: node_js

node_js:
  - "11.0"
  - "10.0"
  - "9.0"

notifications:
  email:
    on_success: always
    on_failure: always

install:
  - npm install -g codecov

script:
  - npm install
  - npm run test

after_success:
  # publish coverage info to coveralls
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && [[ "${TRAVIS_JOB_NUMBER}" = *".1"* ]]; then
      cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js;
      bash scripts/release.sh;
      bash scripts/publish-docs.sh;
    fi
